### ISSUE TITLE
Charts / Numeric Display - handle <1% data and "no data" states

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#151]
- [x] Where chart has no data, the message should be “No data provided for this year.”
- [ ] Percent values can be rounded to nearest integer (as they are currently), but should never round down to zero -- use "<1%" instead.

**Comment by james-minton** [comment]
Re: the 2nd item above, for example in the below image the tooltip should read "<1%" because there are some transgender people (6) in solitary in this state. For places where the number is actually zero, 0% is fine though.

<img width="1318" alt="Screen Shot 2022-11-01 at 2 56 27 AM" src="https://user-images.githubusercontent.com/33635008/199176958-917defd7-341c-44c1-a6b7-5e4d948c7cfb.png">

**Comment by aarondentrodev** [comment]
@james-minton The first one is finished, second one is partially done. @lizlove will continue on this.
