### ISSUE TITLE
"Explore the Data" menu is triggered when hovering anywhere in the hero

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#165]
Steps to reproduce:

1. In desktop mode (at least on Chrome/Mac), hover "explore the data" menu item
2. Move cursor out of the menu area to close it
3. Hover back anywhere in the hero; menu will be re-triggered (it should only appear when hovering the menu item)

https://user-images.githubusercontent.com/33635008/199042116-8a3498bd-e459-4ae4-86b8-89f731c9aa9d.mp4

**Comment by cfhull** [comment]
Just a note for whoever works on this. The issue is that the menu is open while being hovered over, so if you move the cursor back over where the menu was before the animation is complete and the element is removed from the dom, it will reopen the menu. 

The fix is probably to add `pointer-events: none` during the close animation, or something similar.
