### ISSUE TITLE
Separate content and layout, establish content management workflow

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#37]
- [ ] Establish system for non-coder content entry:
  - [ ] content on ancillary pages (everything _besides_ Home, State & Federal Overview, and individual jurisdictions) should be separated from layout, so that it is not hardcoded and a non-coder can manage content. MDX or other markdown-style content files that can accommodate formatting are preferred, so they can be integrated with a CMS at some point, such as [Netlify CMS.](https://www.netlifycms.org/)
  - [ ] we may not have time to set up a CMS in advance of launch. Creating a separate branch for content management via MDX files, and letting content managers directly edit these files in the repo on the web, may be a viable option?
- [ ] replace all lorem ipsum and make sure all links go where they should(content/project manager will do this)

**Comment by achlong** [comment]
Yup, Chris let's sync. My original thought was to put everything into sheets, but there's some text formatting that might not transfer well in sheets. James suggested mardkdown, which I'm not familiar with but can learn.

**Comment by cfhull** [comment]
I took a quick glance at Netlify CMS docs. I honestly don't think it would be that hard to set up. I could probably knock it out in a day or two once I get the hang of it. If you want, I can try to set it up for one of the pages to get an idea of what it would take.

If you do want to wait to set up the CMS, then I think either Sheets or Markdown is probably fine.  I don't think the formatting is too complex for Sheets. I think we could create a sheet for each page and have each row represent a "section" of content with the columns defining each part of the section, depending on the page. I can help define those if needed.

**Comment by james-minton** [comment]
@cfhull for my understanding, how well does formatting like **bold text** and hyperlinks (both on-site and off-) work with Sheets? I think our content managers could work well enough with HTML tags for this if needed, but if there's a way to pass through formatting without having to do that, it would probably be even better. 

I'm just hoping to create efficiencies here, but I also understand we have tradeoffs in terms of time spent on making the content management be markdown-like or done in a CMS, so all this to say: I'm for what gets it done with the least grief :-)

**Comment by cfhull** [comment]
Google sheets can handle rich text like your asking. My concern would be converting that into HTML. You could theoretically make the entire reports page, for example, in rich text, but that wouldn't translate into HTML very well and would give far too much control to the future CMS in defining the page layout.

We would likely want to define a schema that the future CMS would use to build our react pages to expect the correct data, and each page would be different.

As an example, we could define a schema in the netlify CMS that would take a Report name, report URL, list of citations, and a description (description could be rich text), and it outputs a markdown file. In the mean time, we could have sheets have a column for each of those values, and copy paste them into netlify cms in the future.

It really depends on what the format of the CMS data would look like, and mimicking that with sheets or something else.

One clever option might be do format the markdownin the style that Netlify CMS will create, so that when we create the schemas in netlify CMS, they will automatically pick up the content.

https://www.netlifycms.org/docs/add-to-your-site/#collections

**Comment by cfhull** [comment]
Yes. As long as we're defining the FrontMatter data correctly for the pages, and not just using Markdown to render the entirety of the page.
